iterations: 30000
final_step_to_split: 9000

max_sh_degree: 3
position_lr: 0.00001
position_lr_final: 0.0000001
feature_lr: 0.01
feature_lr_final: 0.0001
scale_params_lr: 0.05
scale_params_lr_final: 0.001
nurbs_weights_lr: 0.001
nurbs_weights_lr_final: 0.00001

lambda_dssim: 0.85
resolution_scale: 1.0
resolution: 8
split_every: 1500
start_splitting_from: 3000
stop_splitting: 11000
decay_factor: 0.95
step_size: 1
debug: false
random_background: true
device: 'cuda'
